version: '3.9'
services:
  server:
    build: ./server
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
    restart: always

  client:
    build: ./client
    ports:
      - "3000:80"
    restart: always
